version: '3.9'

services:
  thunderlink-nodejs-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-4001}:4001"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
