version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-secure
    ports:
      - "5671:5671"   # TLS
      - "15672:15672" # management UI
    # volumes:
    #   - ./certs:/certs
    #   - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    hostname: localhost